### ISSUE TITLE
runing local error

### ISSUE THREAD

**Issue by saeedrahmo** [Radinvafaei/react-e-commerce-template#1]
i faced to this error when i run locally 

`Nav(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

im new with react, i think maybe the problem is for how to use examplejson.
how can i fix that issue?

**Comment by sumitmoga** [comment]
I think you didn't run json server

**Comment by devgreek** [comment]
> I think you didn't run json server

please a provide a json server api sample to run
